MODELDIR = "environments/connect4/models/"
EXPMODELDIR = "environments/connect4/exploiter_models/"
WINRATES_DICT_PATH = 'data/winrates.json'
TMPMODELDIR = "logs/"
WINDOW_MODELS = 50
THRESHOLD = 0.8
THRESHOLD_EXP = 0.8
GAMES_PER_OPPONENT_EVAL = 20
EVAL_GAMES = WINDOW_MODELS * GAMES_PER_OPPONENT_EVAL 